/*

 SHIP.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char shipSprite[] =
{
  0x00,0x24,0x00,0x24,0x3C,0x3C,0x66,0x7E,
  0xE7,0xDB,0xA5,0x99,0xA5,0x99,0xFF,0xFF
};

/* End of SHIP.C */
